# CUDA
cuda_devices: '0'   # multi-gpu training is available

# Network
network:
  generator:
    k: 8
    feat_dim: 128
    res_conv_dim: 128
  discriminator: # discriminator is not used in test/evaluation
    k: 8
    feat_dim: 64
    res_conv_dim: 64

# Test dataset
dataset:
  input_dir: '../data/input'
  gt_dir: '../data/gt'
  pred_dir: '../data/pred_Res_GCN'
#  pred_dir: '../data/pred_AR_GCN'

load_model: '../ckpt/AR_GCN/pre_result_80_0.000353.pt'
#load_model: '../ckpt/AR_GCN/gan_result_40_3.087515.pt'